dist:     trusty
sudo:     required

language: cpp       
                    

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - BUILD_CONFIGURATION=Debug
    - BUILD_CONFIGURATION=Release

install:
    - pip3 install conan
  
script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - cmake --build .
