dist:     trusty
sudo:     false

language: cpp       
                    

os:
  - linux

compiler:
  - gcc

env:
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

os: linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.9
  env:
     - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
    
install:
  - pyenv global 3.6
  - pip install --user conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
  - cmake --build .
