language: cpp

matrix:
  include:
    - name: linux, gcc-9
      os: linux
      dist: bionic
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
        - CMAKE_ARCH=""

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9-multilib

    - name: linux, gcc-10
      os: linux
      dist: focal
      env:
        - GCC_VER="10"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
        - CMAKE_ARCH=""
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10-multilib

    - name: linux, clang-9
      os: linux
      dist: bionic
      env:
        - CLANG_VER="9"
        - MATRIX_EVAL="CC=clang-${CLANG_VER} && CXX=clang++-${CLANG_VER}"
        - CMAKE_ARCH=""
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9-multilib
            - clang-9

    - name: linux, clang-10
      os: linux
      dist: bionic
      env:
        - CLANG_VER="10"
        - MATRIX_EVAL="CC=clang-${CLANG_VER} && CXX=clang++-${CLANG_VER}"
        - CMAKE_ARCH=""
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10-multilib # for libstdc++
            - clang-10

before_install:
  - eval "${MATRIX_EVAL}"
    
install:
  - pyenv global 3.7.1 || true # for bionic
  - pip install --user conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
