dist:     trusty
sudo:     false

language: cpp       
                    

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - BUILD_CONFIGURATION=Debug
    - BUILD_CONFIGURATION=Release

addons:
    apt:
        packages:
            - python3
            - python3-pip
        
install:
    - pyenv global 3.6
    - pip3 install --user -U setuptools
    - pip3 install --user conan
  
script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - cmake --build .
